module.exports = {
  version: '0.1',
  language: 'en',
  minWordLength: 4,
  words: [
    'antd',
    'commitlint',
    'DBAPI',
    'Wechat',
    'requied',
    'stylelintrc',
    'stylelintignore',
    'MIDP',
    'SymbianOS',
    'NOKIA',
    'SAMSUNG',
    'LG',
    'NEC',
    'TCL',
    'Alcatel',
    'BIRD',
    'DBTEL',
    'Dopod',
    'PHILIPS',
    'HAIER',
    'LENOVO',
    'MOT-',
    'Nokia',
    'SonyEricsson',
    'SIE-',
    'Amoi',
    'ZTE',
  ],
  ignorePaths: [
    '**/*.svg',
    '**/*.sh',
    '**/*.conf',
    '**/*.png',
    '**/*.json',
    '**/*.lock',
    '**/*.ttf',
    '**/*.otf',
    '**/*.woff',
    '**/*.ogg',
    '**/*.yml',
    '**/*.yaml',
    '.gitignore',
    '.prettierrc',
    '.prettierignore',
    '.eslintrc.js',
    '.eslintignore',
    '.stylelintrc.js',
    '.stylelintignore',
    'README.md',
  ],
};
